//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class FshCommand {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal FshCommand() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.FshCommand", typeof(FshCommand).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to fsh/qfs file.
    /// </summary>
    internal static string Arg1 {
        get {
            return ResourceManager.GetString("Arg1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Path to the FSH/QFS file..
    /// </summary>
    internal static string Arg1Description {
        get {
            return ResourceManager.GetString("Arg1Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to blob name.
    /// </summary>
    internal static string BlobInfo_Arg1 {
        get {
            return ResourceManager.GetString("BlobInfo_Arg1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Specifies the name of the blob to get the information about. If omitted, ths tool will print the information of all blobs in the FSH file..
    /// </summary>
    internal static string BlobInfo_Arg1Help {
        get {
            return ResourceManager.GetString("BlobInfo_Arg1Help", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Blob Name: {0}.
    /// </summary>
    internal static string BlobInfo_BlobName {
        get {
            return ResourceManager.GetString("BlobInfo_BlobName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to No such blob entry has been found in the specified FSH file..
    /// </summary>
    internal static string BlobInfo_Fail {
        get {
            return ResourceManager.GetString("BlobInfo_Fail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Displays general information about the specified FSH blob..
    /// </summary>
    internal static string BlobInfo_Help {
        get {
            return ResourceManager.GetString("BlobInfo_Help", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Blob resolution: {0}x{1}.
    /// </summary>
    internal static string BlobInfo_PrintBlobInfo1 {
        get {
            return ResourceManager.GetString("BlobInfo_PrintBlobInfo1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Pixel format: {0}.
    /// </summary>
    internal static string BlobInfo_PrintBlobInfo2 {
        get {
            return ResourceManager.GetString("BlobInfo_PrintBlobInfo2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Rotation axis: X:{0}, Y:{1}.
    /// </summary>
    internal static string BlobInfo_PrintBlobInfo3 {
        get {
            return ResourceManager.GetString("BlobInfo_PrintBlobInfo3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Image offset: X:{0}, Y:{1}.
    /// </summary>
    internal static string BlobInfo_PrintBlobInfo4 {
        get {
            return ResourceManager.GetString("BlobInfo_PrintBlobInfo4", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Pixel data size: {0}.
    /// </summary>
    internal static string BlobInfo_PrintBlobInfo5 {
        get {
            return ResourceManager.GetString("BlobInfo_PrintBlobInfo5", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Footer data: {0}.
    /// </summary>
    internal static string BlobInfo_PrintBlobInfo6 {
        get {
            return ResourceManager.GetString("BlobInfo_PrintBlobInfo6", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Blob sizes will be formatted in human-readable format..
    /// </summary>
    internal static string Common_HumanOptionHelp {
        get {
            return ResourceManager.GetString("Common_HumanOptionHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Could not load the specified file as a FSH file: {0}.
    /// </summary>
    internal static string Compress_Fail {
        get {
            return ResourceManager.GetString("Compress_Fail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Converts a FSH file into a QFS file..
    /// </summary>
    internal static string Compress_Help {
        get {
            return ResourceManager.GetString("Compress_Help", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Specifies a file to write the compressed FSH into. If omitted, the compressed data will be written to stdout..
    /// </summary>
    internal static string Compress_OutputOptionHelp {
        get {
            return ResourceManager.GetString("Compress_OutputOptionHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Could not load the specified file as a FSH file: {0}.
    /// </summary>
    internal static string Decompress_Fail {
        get {
            return ResourceManager.GetString("Decompress_Fail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Converts a QFS file into a FSH file..
    /// </summary>
    internal static string Decompress_Help {
        get {
            return ResourceManager.GetString("Decompress_Help", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Specifies a file to write the decompressed FSH into. If omitted, the compressed data will be written to stdout..
    /// </summary>
    internal static string Decompress_OutputOptionHelp {
        get {
            return ResourceManager.GetString("Decompress_OutputOptionHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Performs operations on FSH and QFS files..
    /// </summary>
    internal static string Description {
        get {
            return ResourceManager.GetString("Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to File format to use when exporting the blobs to images..
    /// </summary>
    internal static string Extract_FormatOptionHelp {
        get {
            return ResourceManager.GetString("Extract_FormatOptionHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Extracts an image blob from within the specified FSH..
    /// </summary>
    internal static string Extract_Help {
        get {
            return ResourceManager.GetString("Extract_Help", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Output directory to write the blob(s) into. Defaults to the current path..
    /// </summary>
    internal static string Extract_OutdirOptionHelp {
        get {
            return ResourceManager.GetString("Extract_OutdirOptionHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to blob(s) regex.
    /// </summary>
    internal static string Extract_RegexArg {
        get {
            return ResourceManager.GetString("Extract_RegexArg", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Expression/regex that indicates the blob(s) to be extracted from within the specified FSH. If omitted, all blobs will be extracted..
    /// </summary>
    internal static string Extract_RegexArgHelp {
        get {
            return ResourceManager.GetString("Extract_RegexArgHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Displays general information about the FSH/QFS file.
    /// </summary>
    internal static string Info_Help {
        get {
            return ResourceManager.GetString("Info_Help", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Blobs in FSH: {0}.
    /// </summary>
    internal static string Info_Info1 {
        get {
            return ResourceManager.GetString("Info_Info1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Directory ID: {0}.
    /// </summary>
    internal static string Info_Info2 {
        get {
            return ResourceManager.GetString("Info_Info2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to File size: {0}.
    /// </summary>
    internal static string Info_Info3 {
        get {
            return ResourceManager.GetString("Info_Info3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Is FSH file compressed: yes.
    /// </summary>
    internal static string Info_Info4 {
        get {
            return ResourceManager.GetString("Info_Info4", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Uncompressed payload size: {0}.
    /// </summary>
    internal static string Info_Info5 {
        get {
            return ResourceManager.GetString("Info_Info5", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Compression ratio: {0:f2}:1.
    /// </summary>
    internal static string Info_Info6 {
        get {
            return ResourceManager.GetString("Info_Info6", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Is FSH file compressed: no.
    /// </summary>
    internal static string Info_Info7 {
        get {
            return ResourceManager.GetString("Info_Info7", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The blob offsets will be presented in decimal format..
    /// </summary>
    internal static string Ls_DecimalOptionHelp {
        get {
            return ResourceManager.GetString("Ls_DecimalOptionHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Enumerates all blobs on the FSH/QFS file..
    /// </summary>
    internal static string Ls_Help {
        get {
            return ResourceManager.GetString("Ls_Help", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Includes the blob offset in the listing..
    /// </summary>
    internal static string Ls_OffsetOptionHelp {
        get {
            return ResourceManager.GetString("Ls_OffsetOptionHelp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Includes the blob size in the listing..
    /// </summary>
    internal static string Ls_SizeOptionHelp {
        get {
            return ResourceManager.GetString("Ls_SizeOptionHelp", resourceCulture);
        }
    }
}
