//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VivCommand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VivCommand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.VivCommand", typeof(VivCommand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string Add_Arg1 {
            get {
                return ResourceManager.GetString("Add_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the file to be added..
        /// </summary>
        internal static string Add_Arg1Help {
            get {
                return ResourceManager.GetString("Add_Arg1Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified VIV file contains &apos;{0}&apos; already..
        /// </summary>
        internal static string Add_Fail {
            get {
                return ResourceManager.GetString("Add_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force add the file, even if it exists already on the VIV file..
        /// </summary>
        internal static string Add_ForceHelp {
            get {
                return ResourceManager.GetString("Add_ForceHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a file to the VIV..
        /// </summary>
        internal static string Add_Help {
            get {
                return ResourceManager.GetString("Add_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name of the file. If omitted, the current file name wil be used..
        /// </summary>
        internal static string Add_NameHelp {
            get {
                return ResourceManager.GetString("Add_NameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viv file.
        /// </summary>
        internal static string Arg1 {
            get {
                return ResourceManager.GetString("Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the VIV file..
        /// </summary>
        internal static string Arg1Description {
            get {
                return ResourceManager.GetString("Arg1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs operations on VIV files..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) regex.
        /// </summary>
        internal static string Extract_Arg1 {
            get {
                return ResourceManager.GetString("Extract_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name/regex that indicates the file(s) to be extracted from within the specified VIV. If omitted, all files will be extracted..
        /// </summary>
        internal static string Extract_Arg1Help {
            get {
                return ResourceManager.GetString("Extract_Arg1Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory to write the file(s) into. Defaults to the current path..
        /// </summary>
        internal static string Extract_DirectoryHelp {
            get {
                return ResourceManager.GetString("Extract_DirectoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts a file from within the specified VIV..
        /// </summary>
        internal static string Extract_Help {
            get {
                return ResourceManager.GetString("Extract_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header signature: 0x{0} ({1}).
        /// </summary>
        internal static string Info_1 {
            get {
                return ResourceManager.GetString("Info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size in header: {0} ({1}).
        /// </summary>
        internal static string Info_2 {
            get {
                return ResourceManager.GetString("Info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated file size: {0} ({1}).
        /// </summary>
        internal static string Info_3 {
            get {
                return ResourceManager.GetString("Info_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual file size: {0} ({1}).
        /// </summary>
        internal static string Info_4 {
            get {
                return ResourceManager.GetString("Info_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0}.
        /// </summary>
        internal static string Info_5 {
            get {
                return ResourceManager.GetString("Info_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data pool offset: {0}.
        /// </summary>
        internal static string Info_6 {
            get {
                return ResourceManager.GetString("Info_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets basic information on the VIV file..
        /// </summary>
        internal static string Info_Help {
            get {
                return ResourceManager.GetString("Info_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file offsets will be presented in decimal format..
        /// </summary>
        internal static string Ls_DecHelp {
            get {
                return ResourceManager.GetString("Ls_DecHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates all files on the VIV file..
        /// </summary>
        internal static string Ls_Help {
            get {
                return ResourceManager.GetString("Ls_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File sizes will be formatted in human-readable format..
        /// </summary>
        internal static string Ls_HumanHelp {
            get {
                return ResourceManager.GetString("Ls_HumanHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the file offset in the listing..
        /// </summary>
        internal static string Ls_OffsetHelp {
            get {
                return ResourceManager.GetString("Ls_OffsetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the file size in the listing..
        /// </summary>
        internal static string Ls_SizeHelp {
            get {
                return ResourceManager.GetString("Ls_SizeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string Read_Arg1 {
            get {
                return ResourceManager.GetString("Read_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a file name..
        /// </summary>
        internal static string Read_Fail1 {
            get {
                return ResourceManager.GetString("Read_Fail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified VIV file does not contain &apos;{0}&apos;..
        /// </summary>
        internal static string Read_Fail2 {
            get {
                return ResourceManager.GetString("Read_Fail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to read from within the specified VIV..
        /// </summary>
        internal static string Read_FileHelp {
            get {
                return ResourceManager.GetString("Read_FileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads a file from within the specified VIV..
        /// </summary>
        internal static string Read_Help {
            get {
                return ResourceManager.GetString("Read_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, indicates the path to write the file into. If omitted, the file will be read to standard output..
        /// </summary>
        internal static string Read_OutputHelp {
            get {
                return ResourceManager.GetString("Read_OutputHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string Rm_Arg1 {
            get {
                return ResourceManager.GetString("Rm_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to be removed..
        /// </summary>
        internal static string Rm_Arg1Help {
            get {
                return ResourceManager.GetString("Rm_Arg1Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not exist in the specified VIV file..
        /// </summary>
        internal static string Rm_Fail {
            get {
                return ResourceManager.GetString("Rm_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a file from the VIV file..
        /// </summary>
        internal static string Rm_Help {
            get {
                return ResourceManager.GetString("Rm_Help", resourceCulture);
            }
        }
    }
}
