namespace TheXDS.Vivianne.Resources.Strings.Component.Application;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class CommandLineStartup 
{
	private static global::System.Resources.ResourceManager resourceMan;
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public CommandLineStartup()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Component.Application.CommandLineStartup", typeof(CommandLineStartup).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to Operation not permitted.
	/// </summary>
	public static string OperationNotPermitted => ResourceManager.GetString("OperationNotPermitted", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to This operation requires elevated privileges..
	/// </summary>
	public static string OperationRequiresElevation => ResourceManager.GetString("OperationRequiresElevation", Culture);
}
