//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.ViewModels {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FshEditorViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FshEditorViewModel() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.ViewModels.FshEditorViewModel", typeof(FshEditorViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add texture.
        /// </summary>
        public static string AddTexture {
            get {
                return ResourceManager.GetString("AddTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a file to add as a new texture.
        /// </summary>
        public static string AddTexturePrompt {
            get {
                return ResourceManager.GetString("AddTexturePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coords editor.
        /// </summary>
        public static string CoordsEditor {
            get {
                return ResourceManager.GetString("CoordsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dasboard editor.
        /// </summary>
        public static string DashEditor {
            get {
                return ResourceManager.GetString("DashEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to export the current footer data for this FSH blob?.
        /// </summary>
        public static string ExportFooterConfirm {
            get {
                return ResourceManager.GetString("ExportFooterConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FSH blob ID.
        /// </summary>
        public static string FshId {
            get {
                return ResourceManager.GetString("FshId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the ID to use for the new texture.
        /// </summary>
        public static string FshNewId {
            get {
                return ResourceManager.GetString("FshNewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FSH pixel format.
        /// </summary>
        public static string FshPixelFormat {
            get {
                return ResourceManager.GetString("FshPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a pixel format for the new texture.
        /// </summary>
        public static string FshPixelFormatPrompt {
            get {
                return ResourceManager.GetString("FshPixelFormatPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the new ID to use for the &apos;{0}&apos; FSH texture.
        /// </summary>
        public static string FshXNewId {
            get {
                return ResourceManager.GetString("FshXNewId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import blob footer.
        /// </summary>
        public static string ImportBlobFooter {
            get {
                return ResourceManager.GetString("ImportBlobFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid FSH blob ID.
        /// </summary>
        public static string InvalidFshId {
            get {
                return ResourceManager.GetString("InvalidFshId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A FSH file must contain at least one FSH texture..
        /// </summary>
        public static string RemoveLastFshDetails {
            get {
                return ResourceManager.GetString("RemoveLastFshDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot remove FSH texture.
        /// </summary>
        public static string RemoveLastFshError {
            get {
                return ResourceManager.GetString("RemoveLastFshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove {0}.
        /// </summary>
        public static string RemoveX {
            get {
                return ResourceManager.GetString("RemoveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove &apos;{0}&apos; from the FSH?.
        /// </summary>
        public static string RemoveXDetails {
            get {
                return ResourceManager.GetString("RemoveXDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replace &apos;{0}&apos;.
        /// </summary>
        public static string ReplaceFsh {
            get {
                return ResourceManager.GetString("ReplaceFsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a file to replace &apos;{0}&apos; with.
        /// </summary>
        public static string ReplaceFshPrompt {
            get {
                return ResourceManager.GetString("ReplaceFshPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save blob footer as.
        /// </summary>
        public static string SaveBlobFooterAs {
            get {
                return ResourceManager.GetString("SaveBlobFooterAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to save {0}?.
        /// </summary>
        public static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save texture as.
        /// </summary>
        public static string SaveTextureAs {
            get {
                return ResourceManager.GetString("SaveTextureAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsaved changes.
        /// </summary>
        public static string Unsaved {
            get {
                return ResourceManager.GetString("Unsaved", resourceCulture);
            }
        }
    }
}
