//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FceCommand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FceCommand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.FceCommand", typeof(FceCommand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts an FCE from one format to another..
        /// </summary>
        internal static string Convert_description {
            get {
                return ResourceManager.GetString("Convert_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type specified..
        /// </summary>
        internal static string DoRename_InvalidTypeSpecified {
            get {
                return ResourceManager.GetString("DoRename_InvalidTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dummy with the same name already exists..
        /// </summary>
        internal static string Dummy_duplicated {
            get {
                return ResourceManager.GetString("Dummy_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumps the contents of the data tables inside the FCE file..
        /// </summary>
        internal static string Fce_dumpOption_help {
            get {
                return ResourceManager.GetString("Fce_dumpOption_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fce file.
        /// </summary>
        internal static string Fce_FileArg {
            get {
                return ResourceManager.GetString("Fce_FileArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the FCE file..
        /// </summary>
        internal static string Fce_FileArgHelp {
            get {
                return ResourceManager.GetString("Fce_FileArgHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs operations on FCE files..
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be zero or a positive integer..
        /// </summary>
        internal static string Index_error {
            get {
                return ResourceManager.GetString("Index_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is out of range..
        /// </summary>
        internal static string IndexIsOutOfRange {
            get {
                return ResourceManager.GetString("IndexIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets information on the FCE file..
        /// </summary>
        internal static string Info_help {
            get {
                return ResourceManager.GetString("Info_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerates the objects that exist inside the FCE file..
        /// </summary>
        internal static string Ls_help {
            get {
                return ResourceManager.GetString("Ls_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part with the same name already exists..
        /// </summary>
        internal static string Name_duplicated {
            get {
                return ResourceManager.GetString("Name_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        internal static string Name_empty {
            get {
                return ResourceManager.GetString("Name_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the new name of the object..
        /// </summary>
        internal static string NewName_Help {
            get {
                return ResourceManager.GetString("NewName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the index of the object to rename..
        /// </summary>
        internal static string ObjIndex_Help {
            get {
                return ResourceManager.GetString("ObjIndex_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file name. If not specified, the conversion will happen in-place..
        /// </summary>
        internal static string OutOptionHelp {
            get {
                return ResourceManager.GetString("OutOptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the name of a part or dummy..
        /// </summary>
        internal static string Rename_Help {
            get {
                return ResourceManager.GetString("Rename_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of object to rename..
        /// </summary>
        internal static string SpecificFceObjectType_Help {
            get {
                return ResourceManager.GetString("SpecificFceObjectType_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the kind of object to be listed..
        /// </summary>
        internal static string TypeOption_Help {
            get {
                return ResourceManager.GetString("TypeOption_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown FCE version..
        /// </summary>
        internal static string UnknownFCEVersion {
            get {
                return ResourceManager.GetString("UnknownFCEVersion", resourceCulture);
            }
        }
    }
}
