//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashEditorView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashEditorView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.DashEditorView", typeof(DashEditorView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dials.
        /// </summary>
        public static string Basics {
            get {
                return ResourceManager.GetString("Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center coordinates.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center offset.
        /// </summary>
        public static string CenterOff {
            get {
                return ResourceManager.GetString("CenterOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color coordinates.
        /// </summary>
        public static string DialColor {
            get {
                return ResourceManager.GetString("DialColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial base width.
        /// </summary>
        public static string DialWidthBase {
            get {
                return ResourceManager.GetString("DialWidthBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial tip width.
        /// </summary>
        public static string DialWidthTip {
            get {
                return ResourceManager.GetString("DialWidthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear coordinates.
        /// </summary>
        public static string GearCoords {
            get {
                return ResourceManager.GetString("GearCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        public static string Gears {
            get {
                return ResourceManager.GetString("Gears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value coordinates.
        /// </summary>
        public static string MaxCoords {
            get {
                return ResourceManager.GetString("MaxCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value coordinates.
        /// </summary>
        public static string MinCoords {
            get {
                return ResourceManager.GetString("MinCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedometer.
        /// </summary>
        public static string Speedometer {
            get {
                return ResourceManager.GetString("Speedometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering wheel placement.
        /// </summary>
        public static string SteeringWheelProps {
            get {
                return ResourceManager.GetString("SteeringWheelProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tachometer.
        /// </summary>
        public static string Tacho {
            get {
                return ResourceManager.GetString("Tacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip offset.
        /// </summary>
        public static string TipOff {
            get {
                return ResourceManager.GetString("TipOff", resourceCulture);
            }
        }
    }
}
