//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BnkEditorViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BnkEditorViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.ViewModels.BnkEditorViewModel", typeof(BnkEditorViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add audio padding.
        /// </summary>
        public static string AddAudioPadding {
            get {
                return ResourceManager.GetString("AddAudioPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of samples of silence to add to the beginning and the end of the audio stream..
        /// </summary>
        public static string AddAudioPaddingText {
            get {
                return ResourceManager.GetString("AddAudioPaddingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK stream.
        /// </summary>
        public static string BNKStream {
            get {
                return ResourceManager.GetString("BNKStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK v2 parsers do not (or at least should not) support alternate audio streams. If you continue, these alternate streams will be lost. Are you sure you want to save this BNK using the v2 format?.
        /// </summary>
        public static string BNKv2_AltStreamWarning {
            get {
                return ResourceManager.GetString("BNKv2_AltStreamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK version.
        /// </summary>
        public static string BNKVersion {
            get {
                return ResourceManager.GetString("BNKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export loop.
        /// </summary>
        public static string ExportLoop {
            get {
                return ResourceManager.GetString("ExportLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got to settings.
        /// </summary>
        public static string GoToSettings {
            get {
                return ResourceManager.GetString("GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Alt stream.
        /// </summary>
        public static string ImportAltStream {
            get {
                return ResourceManager.GetString("ImportAltStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject padding.
        /// </summary>
        public static string InjectPadding {
            get {
                return ResourceManager.GetString("InjectPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK cleanup upon save is enabled in the settings. Please disable it before using this feature..
        /// </summary>
        public static string InjectPaddingCleanupError {
            get {
                return ResourceManager.GetString("InjectPaddingCleanupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of padding bytes to add in between this audio stream and the next. This should help alleviate audio stream data to overlap each other in game..
        /// </summary>
        public static string InjectPaddingText {
            get {
                return ResourceManager.GetString("InjectPaddingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop length.
        /// </summary>
        public static string LoopLength {
            get {
                return ResourceManager.GetString("LoopLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop start.
        /// </summary>
        public static string LoopStart {
            get {
                return ResourceManager.GetString("LoopStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BNK file format does not support nested alt streams..
        /// </summary>
        public static string NestedAltStreamsError {
            get {
                return ResourceManager.GetString("NestedAltStreamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio stream loaded.
        /// </summary>
        public static string NoAudioStreamLoaded {
            get {
                return ResourceManager.GetString("NoAudioStreamLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio stream does not contain a looping section..
        /// </summary>
        public static string NoLoop {
            get {
                return ResourceManager.GetString("NoLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize.
        /// </summary>
        public static string Normalize {
            get {
                return ResourceManager.GetString("Normalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a desired max volume level relative to 1.0.
        /// </summary>
        public static string NormalizeText {
            get {
                return ResourceManager.GetString("NormalizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play looping.
        /// </summary>
        public static string PlayLooping {
            get {
                return ResourceManager.GetString("PlayLooping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unused data.
        /// </summary>
        public static string RemoveUnusedData {
            get {
                return ResourceManager.GetString("RemoveUnusedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the unused data from the BNK will reduce its size, but it will remove the data outside of the looping sections of the streams with looping audio. This action cannot be undone. Are you sure you want to optimize the BNK and remove the unused data?.
        /// </summary>
        public static string RemoveUnusedDataQuestion {
            get {
                return ResourceManager.GetString("RemoveUnusedDataQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        public static string ShowInfo {
            get {
                return ResourceManager.GetString("ShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        public static string Stream {
            get {
                return ResourceManager.GetString("Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported audio stream..
        /// </summary>
        public static string UnsupportedAudioStream {
            get {
                return ResourceManager.GetString("UnsupportedAudioStream", resourceCulture);
            }
        }
    }
}
