//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VivEditorViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VivEditorViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.ViewModels.VivEditorViewModel", typeof(VivEditorViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove &apos;{0}&apos;?.
        /// </summary>
        public static string AreYouSureYouWantToRemoveX {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToRemoveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        public static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New from template.
        /// </summary>
        public static string NewFromTemplate {
            get {
                return ResourceManager.GetString("NewFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+click to open externally.
        /// </summary>
        public static string OpenExternally {
            get {
                return ResourceManager.GetString("OpenExternally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &apos;{0}&apos;.
        /// </summary>
        public static string RemoveX {
            get {
                return ResourceManager.GetString("RemoveX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new name of the file.
        /// </summary>
        public static string RenameHelp {
            get {
                return ResourceManager.GetString("RenameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace file.
        /// </summary>
        public static string ReplaceFile {
            get {
                return ResourceManager.GetString("ReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace &apos;{0}&apos;.
        /// </summary>
        public static string ReplaceX {
            get {
                return ResourceManager.GetString("ReplaceX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save VIV file.
        /// </summary>
        public static string SaveVivFile {
            get {
                return ResourceManager.GetString("SaveVivFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save VIV file as....
        /// </summary>
        public static string SaveVivFileAs {
            get {
                return ResourceManager.GetString("SaveVivFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to repace &apos;{0}&apos; with.
        /// </summary>
        public static string SelectAFileToRepaceXWith {
            get {
                return ResourceManager.GetString("SelectAFileToRepaceXWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a template to create a new file in the VIV directory..
        /// </summary>
        public static string SelectATemplate {
            get {
                return ResourceManager.GetString("SelectATemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exist. Do you want to replace it?.
        /// </summary>
        public static string TheFileXAlreadyExist {
            get {
                return ResourceManager.GetString("TheFileXAlreadyExist", resourceCulture);
            }
        }
    }
}
