//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerialNumberAnalyzer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerialNumberAnalyzer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Tools.SerialNumberAnalyzer", typeof(SerialNumberAnalyzer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarModel path.
        /// </summary>
        internal static string CarModelPath {
            get {
                return ResourceManager.GetString("CarModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading &apos;carp.txt&apos;: {0}. Skipping....
        /// </summary>
        internal static string ErrorLoadingCarpTxt {
            get {
                return ResourceManager.GetString("ErrorLoadingCarpTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading FeData &apos;{0}&apos;: {1}. Skipping....
        /// </summary>
        internal static string ErrorLoadingFeData {
            get {
                return ResourceManager.GetString("ErrorLoadingFeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading VIV file &apos;{0}&apos;: {1}. Skipping....
        /// </summary>
        internal static string ErrorLoadingVIVFile {
            get {
                return ResourceManager.GetString("ErrorLoadingVIVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading &apos;{0}&apos;....
        /// </summary>
        internal static string LoadingX {
            get {
                return ResourceManager.GetString("LoadingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicate/conflicting/missing serial numbers found..
        /// </summary>
        internal static string NoDuplicateConflictingMissingSerialNumbersFound {
            get {
                return ResourceManager.GetString("NoDuplicateConflictingMissingSerialNumbersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully. Number of fixed serial numbers: {0}.
        /// </summary>
        internal static string OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the &apos;CarModel&apos; directory inside NFS3/Gamedata folder..
        /// </summary>
        internal static string SelectTheCarModelDirectoryInsideNFS3GamedataFolder {
            get {
                return ResourceManager.GetString("SelectTheCarModelDirectoryInsideNFS3GamedataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number analyzer.
        /// </summary>
        internal static string SerialNumberAnalyzer {
            get {
                return ResourceManager.GetString("SerialNumberAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing &apos;{0}&apos;....
        /// </summary>
        internal static string WritingX {
            get {
                return ResourceManager.GetString("WritingX", resourceCulture);
            }
        }
    }
}
