//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BnkEditorViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BnkEditorViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.ViewModels.BnkEditorViewModel", typeof(BnkEditorViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ Has alternate audio stream.
        /// </summary>
        public static string BnkNfo_AltStream {
            get {
                return ResourceManager.GetString("BnkNfo_AltStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels: {0}.
        /// </summary>
        public static string BnkNfo_Channels {
            get {
                return ResourceManager.GetString("BnkNfo_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: {0}.
        /// </summary>
        public static string BnkNfo_Duration {
            get {
                return ResourceManager.GetString("BnkNfo_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio stream format: {0}-bit {1}.
        /// </summary>
        public static string BnkNfo_Format {
            get {
                return ResourceManager.GetString("BnkNfo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate: {0} Hz.
        /// </summary>
        public static string BnkNfo_SampleRate {
            get {
                return ResourceManager.GetString("BnkNfo_SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total samples: {0}.
        /// </summary>
        public static string BnkNfo_Samples {
            get {
                return ResourceManager.GetString("BnkNfo_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: {0}.
        /// </summary>
        public static string BnkNfo_Size {
            get {
                return ResourceManager.GetString("BnkNfo_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK stream.
        /// </summary>
        public static string BNKStream {
            get {
                return ResourceManager.GetString("BNKStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK v2 parsers do not (or at least should not) support alternate audio streams. If you continue, these alternate streams will be lost. Are you sure you want to save this BNK using the v2 format?.
        /// </summary>
        public static string BNKv2_AltStreamWarning {
            get {
                return ResourceManager.GetString("BNKv2_AltStreamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK version.
        /// </summary>
        public static string BNKVersion {
            get {
                return ResourceManager.GetString("BNKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export loop.
        /// </summary>
        public static string ExportLoop {
            get {
                return ResourceManager.GetString("ExportLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop length.
        /// </summary>
        public static string LoopLength {
            get {
                return ResourceManager.GetString("LoopLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop start.
        /// </summary>
        public static string LoopStart {
            get {
                return ResourceManager.GetString("LoopStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio stream loaded.
        /// </summary>
        public static string NoAudioStreamLoaded {
            get {
                return ResourceManager.GetString("NoAudioStreamLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio stream does not contain a looping section..
        /// </summary>
        public static string NoLoop {
            get {
                return ResourceManager.GetString("NoLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        public static string ShowInfo {
            get {
                return ResourceManager.GetString("ShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        public static string Stream {
            get {
                return ResourceManager.GetString("Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported audio stream..
        /// </summary>
        public static string UnsupportedAudioStream {
            get {
                return ResourceManager.GetString("UnsupportedAudioStream", resourceCulture);
            }
        }
    }
}
