//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.ViewModels; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class FshEditorViewModel {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal FshEditorViewModel() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.ViewModels.FshEditorViewModel", typeof(FshEditorViewModel).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Add texture.
    /// </summary>
    public static string AddTexture {
        get {
            return ResourceManager.GetString("AddTexture", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select a file to add as a new texture.
    /// </summary>
    public static string AddTexturePrompt {
        get {
            return ResourceManager.GetString("AddTexturePrompt", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Coords editor.
    /// </summary>
    public static string CoordsEditor {
        get {
            return ResourceManager.GetString("CoordsEditor", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Dasboard editor.
    /// </summary>
    public static string DashEditor {
        get {
            return ResourceManager.GetString("DashEditor", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Do you want to export the current footer data for this FSH blob?.
    /// </summary>
    public static string ExportFooterConfirm {
        get {
            return ResourceManager.GetString("ExportFooterConfirm", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to FSH blob ID.
    /// </summary>
    public static string FshId {
        get {
            return ResourceManager.GetString("FshId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Enter the ID to use for the new texture.
    /// </summary>
    public static string FshNewId {
        get {
            return ResourceManager.GetString("FshNewId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to FSH pixel format.
    /// </summary>
    public static string FshPixelFormat {
        get {
            return ResourceManager.GetString("FshPixelFormat", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select a pixel format for the new texture.
    /// </summary>
    public static string FshPixelFormatPrompt {
        get {
            return ResourceManager.GetString("FshPixelFormatPrompt", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Enter the new ID to use for the &apos;{0}&apos; FSH texture.
    /// </summary>
    public static string FshXNewId {
        get {
            return ResourceManager.GetString("FshXNewId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Import blob footer.
    /// </summary>
    public static string ImportBlobFooter {
        get {
            return ResourceManager.GetString("ImportBlobFooter", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invalid FSH blob ID.
    /// </summary>
    public static string InvalidFshId {
        get {
            return ResourceManager.GetString("InvalidFshId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to A FSH file must contain at least one FSH texture..
    /// </summary>
    public static string RemoveLastFshDetails {
        get {
            return ResourceManager.GetString("RemoveLastFshDetails", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot remove FSH texture.
    /// </summary>
    public static string RemoveLastFshError {
        get {
            return ResourceManager.GetString("RemoveLastFshError", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Remove {0}.
    /// </summary>
    public static string RemoveX {
        get {
            return ResourceManager.GetString("RemoveX", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Are you sure you want to remove &apos;{0}&apos; from the FSH?.
    /// </summary>
    public static string RemoveXDetails {
        get {
            return ResourceManager.GetString("RemoveXDetails", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Replace &apos;{0}&apos;.
    /// </summary>
    public static string ReplaceFsh {
        get {
            return ResourceManager.GetString("ReplaceFsh", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select a file to replace &apos;{0}&apos; with.
    /// </summary>
    public static string ReplaceFshPrompt {
        get {
            return ResourceManager.GetString("ReplaceFshPrompt", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Save blob footer as.
    /// </summary>
    public static string SaveBlobFooterAs {
        get {
            return ResourceManager.GetString("SaveBlobFooterAs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Do you want to save {0}?.
    /// </summary>
    public static string SaveConfirm {
        get {
            return ResourceManager.GetString("SaveConfirm", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Save texture as.
    /// </summary>
    public static string SaveTextureAs {
        get {
            return ResourceManager.GetString("SaveTextureAs", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Unsaved changes.
    /// </summary>
    public static string Unsaved {
        get {
            return ResourceManager.GetString("Unsaved", resourceCulture);
        }
    }
}
