//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to read a string outside of file bounds (offset 0x{0:X8}). Returning an empty string instead....
        /// </summary>
        internal static string FeDataSerializer_StringOutOfBounds {
            get {
                return ResourceManager.GetString("FeDataSerializer_StringOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH blob ID must include letters and/or digits only..
        /// </summary>
        internal static string FshBlobBadId {
            get {
                return ResourceManager.GetString("FshBlobBadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH requires blobs to include a 4 character ID..
        /// </summary>
        internal static string FshBlobEmptyId {
            get {
                return ResourceManager.GetString("FshBlobEmptyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH blob ID length mismatch. Please specify a 4 character long ID..
        /// </summary>
        internal static string FshBlobIdTooLong {
            get {
                return ResourceManager.GetString("FshBlobIdTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified ID is already in use..
        /// </summary>
        internal static string FshBlobNewIdInUse {
            get {
                return ResourceManager.GetString("FshBlobNewIdInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown (0x{0:X2}).
        /// </summary>
        internal static string UnknownAsHex {
            get {
                return ResourceManager.GetString("UnknownAsHex", resourceCulture);
            }
        }
    }
}
