//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mappings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mappings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Mappings", typeof(Mappings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZ compressed RGB565.
        /// </summary>
        public static string FasBlobToLabel_LzRgb565 {
            get {
                return ResourceManager.GetString("FasBlobToLabel_LzRgb565", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need For Speed 3 FCE.
        /// </summary>
        public static string FceMagicToString_Fce3 {
            get {
                return ResourceManager.GetString("FceMagicToString_Fce3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need For Speed 4 FCE.
        /// </summary>
        public static string FceMagicToString_Fce4 {
            get {
                return ResourceManager.GetString("FceMagicToString_Fce4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor City Online FCE.
        /// </summary>
        public static string FceMagicToString_Fce4M {
            get {
                return ResourceManager.GetString("FceMagicToString_Fce4M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string FceMagicToString_Unknown {
            get {
                return ResourceManager.GetString("FceMagicToString_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob name.
        /// </summary>
        public static string FshBlobFooterToLabel_BlobName {
            get {
                return ResourceManager.GetString("FshBlobFooterToLabel_BlobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car dashboard data.
        /// </summary>
        public static string FshBlobFooterToLabel_CarDashboard {
            get {
                return ResourceManager.GetString("FshBlobFooterToLabel_CarDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local color palette.
        /// </summary>
        public static string FshBlobFooterToLabel_ColorPalette {
            get {
                return ResourceManager.GetString("FshBlobFooterToLabel_ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal bin attachment.
        /// </summary>
        public static string FshBlobFooterToLabel_MetalBin {
            get {
                return ResourceManager.GetString("FshBlobFooterToLabel_MetalBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No footer data present.
        /// </summary>
        public static string FshBlobFooterToLabel_None {
            get {
                return ResourceManager.GetString("FshBlobFooterToLabel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding zeros.
        /// </summary>
        public static string FshBlobFooterToLabel_Padding {
            get {
                return ResourceManager.GetString("FshBlobFooterToLabel_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit Color with 1 bit alpha channel (ARGB1555).
        /// </summary>
        public static string FshBlobToLabel_Argb1555 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Argb1555", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-bit color with 8-bit alpha channel (ARGB32).
        /// </summary>
        public static string FshBlobToLabel_Argb32 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Argb32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit 4:4:4:4 color (RGBA4444).
        /// </summary>
        public static string FshBlobToLabel_Argb4444 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Argb4444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXT1 compressed texture.
        /// </summary>
        public static string FshBlobToLabel_Dxt1 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Dxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXT3 compressed texture.
        /// </summary>
        public static string FshBlobToLabel_Dxt3 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Dxt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXT4 compressed texture.
        /// </summary>
        public static string FshBlobToLabel_Dxt4 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Dxt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-bit color (256 colors) with palette.
        /// </summary>
        public static string FshBlobToLabel_Indexed8 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Indexed8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZ compressed ARGB1555.
        /// </summary>
        public static string FshBlobToLabel_LzArgb1555 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_LzArgb1555", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZ compressed ARGB32.
        /// </summary>
        public static string FshBlobToLabel_LzArgb32 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_LzArgb32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit color palette.
        /// </summary>
        public static string FshBlobToLabel_Palette16 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Palette16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit color palette, NFS5 variant.
        /// </summary>
        public static string FshBlobToLabel_Palette16Nfs5 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Palette16Nfs5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-bit color palette.
        /// </summary>
        public static string FshBlobToLabel_Palette24 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Palette24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-bit color palette, DOS variant.
        /// </summary>
        public static string FshBlobToLabel_Palette24Dos {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Palette24Dos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-bit color palette.
        /// </summary>
        public static string FshBlobToLabel_Palette32 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Palette32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-bit color without alpha (RGB24).
        /// </summary>
        public static string FshBlobToLabel_Rgb24 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Rgb24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16-bit color (RGB565), no alpha.
        /// </summary>
        public static string FshBlobToLabel_Rgb565 {
            get {
                return ResourceManager.GetString("FshBlobToLabel_Rgb565", resourceCulture);
            }
        }
    }
}
