//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileFilters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileFilters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.FileFilters", typeof(FileFilters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA music track file.
        /// </summary>
        public static string AsfFile {
            get {
                return ResourceManager.GetString("AsfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASF/MUS file.
        /// </summary>
        public static string AsfMusFile {
            get {
                return ResourceManager.GetString("AsfMusFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP bitmap image.
        /// </summary>
        public static string BmpFile {
            get {
                return ResourceManager.GetString("BmpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA sound bank file.
        /// </summary>
        public static string BnkFile {
            get {
                return ResourceManager.GetString("BnkFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFS car performance data.
        /// </summary>
        public static string CarpFile {
            get {
                return ResourceManager.GetString("CarpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common VIV content files.
        /// </summary>
        public static string CommonVIVContentFiles {
            get {
                return ResourceManager.GetString("CommonVIVContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA 3D model.
        /// </summary>
        public static string EA3DModel {
            get {
                return ResourceManager.GetString("EA3DModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-end localized language file.
        /// </summary>
        public static string FeDataFile {
            get {
                return ResourceManager.GetString("FeDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHPI texture.
        /// </summary>
        public static string FshFile {
            get {
                return ResourceManager.GetString("FshFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic NFS game resource file.
        /// </summary>
        public static string GenericFile {
            get {
                return ResourceManager.GetString("GenericFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF image.
        /// </summary>
        public static string GifFile {
            get {
                return ResourceManager.GetString("GifFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG picture.
        /// </summary>
        public static string JpgFile {
            get {
                return ResourceManager.GetString("JpgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUS linear playback metadata.
        /// </summary>
        public static string LinFile {
            get {
                return ResourceManager.GetString("LinFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUS interactive playback metadata.
        /// </summary>
        public static string MapFile {
            get {
                return ResourceManager.GetString("MapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readme file.
        /// </summary>
        public static string MdFile {
            get {
                return ResourceManager.GetString("MdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA interactive music bank file.
        /// </summary>
        public static string MusFile {
            get {
                return ResourceManager.GetString("MusFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures, textures and images.
        /// </summary>
        public static string PictureFile {
            get {
                return ResourceManager.GetString("PictureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphics.
        /// </summary>
        public static string PngFile {
            get {
                return ResourceManager.GetString("PngFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed SHPI texture.
        /// </summary>
        public static string QfsFile {
            get {
                return ResourceManager.GetString("QfsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrueVision TGA.
        /// </summary>
        public static string TgaFile {
            get {
                return ResourceManager.GetString("TgaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIV container file.
        /// </summary>
        public static string VivFile {
            get {
                return ResourceManager.GetString("VivFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAV audio file.
        /// </summary>
        public static string WavFile {
            get {
                return ResourceManager.GetString("WavFile", resourceCulture);
            }
        }
    }
}
