//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileFilters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileFilters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.FileFilters", typeof(FileFilters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP bitmap image.
        /// </summary>
        public static string BMPBitmapImage {
            get {
                return ResourceManager.GetString("BMPBitmapImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNK audio file.
        /// </summary>
        public static string BNKAudioFile {
            get {
                return ResourceManager.GetString("BNKAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common image files.
        /// </summary>
        public static string CommonImageFiles {
            get {
                return ResourceManager.GetString("CommonImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common VIV content files.
        /// </summary>
        public static string CommonVIVContentFiles {
            get {
                return ResourceManager.GetString("CommonVIVContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCE 3D model.
        /// </summary>
        public static string FCE3DModel {
            get {
                return ResourceManager.GetString("FCE3DModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH texture.
        /// </summary>
        public static string FshFile {
            get {
                return ResourceManager.GetString("FshFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH/QFS texture.
        /// </summary>
        public static string FSHQFSTexture {
            get {
                return ResourceManager.GetString("FSHQFSTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF image.
        /// </summary>
        public static string GIFImage {
            get {
                return ResourceManager.GetString("GIFImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG picture.
        /// </summary>
        public static string JPEGPicture {
            get {
                return ResourceManager.GetString("JPEGPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized car FeData.
        /// </summary>
        public static string LocalizedCarFeData {
            get {
                return ResourceManager.GetString("LocalizedCarFeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphics.
        /// </summary>
        public static string PortableNetworkGraphics {
            get {
                return ResourceManager.GetString("PortableNetworkGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QFS texture.
        /// </summary>
        public static string QfsFile {
            get {
                return ResourceManager.GetString("QfsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIV file.
        /// </summary>
        public static string VivFile {
            get {
                return ResourceManager.GetString("VivFile", resourceCulture);
            }
        }
    }
}
