//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FceCleanupTool {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FceCleanupTool() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Tools.FceCleanupTool", typeof(FceCleanupTool).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCE cleanup.
        /// </summary>
        internal static string FCECleanup {
            get {
                return ResourceManager.GetString("FCECleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCE data has been cleaned up..
        /// </summary>
        internal static string FCEDataHasBeenCleanedUp {
            get {
                return ResourceManager.GetString("FCEDataHasBeenCleanedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing: {0}....
        /// </summary>
        internal static string FixingX {
            get {
                return ResourceManager.GetString("FixingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        internal static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problems found.
        /// </summary>
        internal static string NoProblemsFound {
            get {
                return ResourceManager.GetString("NoProblemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing FCE file....
        /// </summary>
        internal static string ParsingFCEFile {
            get {
                return ResourceManager.GetString("ParsingFCEFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file....
        /// </summary>
        internal static string SavingFile {
            get {
                return ResourceManager.GetString("SavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FCE file data is valid..
        /// </summary>
        internal static string TheFCEFileDataIsValid {
            get {
                return ResourceManager.GetString("TheFCEFileDataIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying FCE data....
        /// </summary>
        internal static string VerifyingFCEData {
            get {
                return ResourceManager.GetString("VerifyingFCEData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} problems found....
        /// </summary>
        internal static string XProblemsFound {
            get {
                return ResourceManager.GetString("XProblemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} problems found. Would you like to solve them?.
        /// </summary>
        internal static string XProblemsFoundQuestion {
            get {
                return ResourceManager.GetString("XProblemsFoundQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
