//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashEditorView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashEditorView() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.DashEditorView", typeof(DashEditorView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dials.
        /// </summary>
        public static string Basics {
            get {
                return ResourceManager.GetString("Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center coordinates.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center offset.
        /// </summary>
        public static string CenterOff {
            get {
                return ResourceManager.GetString("CenterOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color coordinates.
        /// </summary>
        public static string DialColor {
            get {
                return ResourceManager.GetString("DialColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dial base width.
        /// </summary>
        public static string DialWidthBase {
            get {
                return ResourceManager.GetString("DialWidthBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dial tip width.
        /// </summary>
        public static string DialWidthTip {
            get {
                return ResourceManager.GetString("DialWidthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gear coordinates.
        /// </summary>
        public static string GearCoords {
            get {
                return ResourceManager.GetString("GearCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gears.
        /// </summary>
        public static string Gears {
            get {
                return ResourceManager.GetString("Gears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum value.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum value coordinates.
        /// </summary>
        public static string MaxCoords {
            get {
                return ResourceManager.GetString("MaxCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum value.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum value coordinates.
        /// </summary>
        public static string MinCoords {
            get {
                return ResourceManager.GetString("MinCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speedometer.
        /// </summary>
        public static string Speedometer {
            get {
                return ResourceManager.GetString("Speedometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steering wheel placement.
        /// </summary>
        public static string SteeringWheelProps {
            get {
                return ResourceManager.GetString("SteeringWheelProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tachometer.
        /// </summary>
        public static string Tacho {
            get {
                return ResourceManager.GetString("Tacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tip offset.
        /// </summary>
        public static string TipOff {
            get {
                return ResourceManager.GetString("TipOff", resourceCulture);
            }
        }
    }
}
