//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeDataPreviewView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeDataPreviewView() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.FeDataPreviewView", typeof(FeDataPreviewView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0 to 100 MPH.
        /// </summary>
        public static string Accel0To100 {
            get {
                return ResourceManager.GetString("Accel0To100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0 to 60 MPH.
        /// </summary>
        public static string Accel0To60 {
            get {
                return ResourceManager.GetString("Accel0To60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceleration.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basic FeData.
        /// </summary>
        public static string BasicFeData {
            get {
                return ResourceManager.GetString("BasicFeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basic properties.
        /// </summary>
        public static string BasicProperties {
            get {
                return ResourceManager.GetString("BasicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brakes.
        /// </summary>
        public static string Brakes {
            get {
                return ResourceManager.GetString("Brakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Braking.
        /// </summary>
        public static string Braking {
            get {
                return ResourceManager.GetString("Braking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Car class.
        /// </summary>
        public static string CarClass {
            get {
                return ResourceManager.GetString("CarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Car ID.
        /// </summary>
        public static string CarId {
            get {
                return ResourceManager.GetString("CarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Car name.
        /// </summary>
        public static string CarName {
            get {
                return ResourceManager.GetString("CarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 1.
        /// </summary>
        public static string Color1 {
            get {
                return ResourceManager.GetString("Color1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 10.
        /// </summary>
        public static string Color10 {
            get {
                return ResourceManager.GetString("Color10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 2.
        /// </summary>
        public static string Color2 {
            get {
                return ResourceManager.GetString("Color2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 3.
        /// </summary>
        public static string Color3 {
            get {
                return ResourceManager.GetString("Color3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 4.
        /// </summary>
        public static string Color4 {
            get {
                return ResourceManager.GetString("Color4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 5.
        /// </summary>
        public static string Color5 {
            get {
                return ResourceManager.GetString("Color5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 6.
        /// </summary>
        public static string Color6 {
            get {
                return ResourceManager.GetString("Color6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 7.
        /// </summary>
        public static string Color7 {
            get {
                return ResourceManager.GetString("Color7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 8.
        /// </summary>
        public static string Color8 {
            get {
                return ResourceManager.GetString("Color8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 9.
        /// </summary>
        public static string Color9 {
            get {
                return ResourceManager.GetString("Color9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displacement.
        /// </summary>
        public static string Displacement {
            get {
                return ResourceManager.GetString("Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driver seat.
        /// </summary>
        public static string DriverSeat {
            get {
                return ResourceManager.GetString("DriverSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Engine.
        /// </summary>
        public static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gearbox.
        /// </summary>
        public static string Gearbox {
            get {
                return ResourceManager.GetString("Gearbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Handling.
        /// </summary>
        public static string Handling {
            get {
                return ResourceManager.GetString("Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History 1.
        /// </summary>
        public static string History1 {
            get {
                return ResourceManager.GetString("History1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History 2.
        /// </summary>
        public static string History2 {
            get {
                return ResourceManager.GetString("History2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History 3.
        /// </summary>
        public static string History3 {
            get {
                return ResourceManager.GetString("History3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History 4.
        /// </summary>
        public static string History4 {
            get {
                return ResourceManager.GetString("History4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History 5.
        /// </summary>
        public static string History5 {
            get {
                return ResourceManager.GetString("History5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History6.
        /// </summary>
        public static string History6 {
            get {
                return ResourceManager.GetString("History6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History 7.
        /// </summary>
        public static string History7 {
            get {
                return ResourceManager.GetString("History7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a History 8.
        /// </summary>
        public static string History8 {
            get {
                return ResourceManager.GetString("History8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is available to AI drivers.
        /// </summary>
        public static string IsAvailableToAI {
            get {
                return ResourceManager.GetString("IsAvailableToAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is bonus car.
        /// </summary>
        public static string IsBonus {
            get {
                return ResourceManager.GetString("IsBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is police car.
        /// </summary>
        public static string IsPolice {
            get {
                return ResourceManager.GetString("IsPolice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum RPM.
        /// </summary>
        public static string MaxRpm {
            get {
                return ResourceManager.GetString("MaxRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tires.
        /// </summary>
        public static string Tires {
            get {
                return ResourceManager.GetString("Tires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top speed.
        /// </summary>
        public static string TopSpeed {
            get {
                return ResourceManager.GetString("TopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Torque.
        /// </summary>
        public static string Torque {
            get {
                return ResourceManager.GetString("Torque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transmission.
        /// </summary>
        public static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight distribution.
        /// </summary>
        public static string WeightDistr {
            get {
                return ResourceManager.GetString("WeightDistr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
