//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VivInfoView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VivInfoView() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.VivInfoView", typeof(VivInfoView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directory size: {0} files.
        /// </summary>
        public static string DirSize {
            get {
                return ResourceManager.GetString("DirSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export all files.
        /// </summary>
        public static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has english (british) FeData.
        /// </summary>
        public static string FeDataBri {
            get {
                return ResourceManager.GetString("FeDataBri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has english (US) FeData.
        /// </summary>
        public static string FeDataEng {
            get {
                return ResourceManager.GetString("FeDataEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has french FeData.
        /// </summary>
        public static string FeDataFre {
            get {
                return ResourceManager.GetString("FeDataFre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has german FeData.
        /// </summary>
        public static string FeDataGer {
            get {
                return ResourceManager.GetString("FeDataGer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has italian FeData.
        /// </summary>
        public static string FeDataIta {
            get {
                return ResourceManager.GetString("FeDataIta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has spanish FeData.
        /// </summary>
        public static string FeDataSpa {
            get {
                return ResourceManager.GetString("FeDataSpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has swedish FeData.
        /// </summary>
        public static string FeDataSwe {
            get {
                return ResourceManager.GetString("FeDataSwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimated file size: {0}.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has basic engine sound effects.
        /// </summary>
        public static string HasBnk {
            get {
                return ResourceManager.GetString("HasBnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has car mesh.
        /// </summary>
        public static string HasCarFce {
            get {
                return ResourceManager.GetString("HasCarFce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has dashboard FSH.
        /// </summary>
        public static string HasDash {
            get {
                return ResourceManager.GetString("HasDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has in-menu FSH car logo.
        /// </summary>
        public static string HasFedataFsh {
            get {
                return ResourceManager.GetString("HasFedataFsh", resourceCulture);
            }
        }
    }
}
