//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CarpEditorView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarpEditorView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.CarpEditorView", typeof(CarpEditorView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aero downforce mult.
        /// </summary>
        public static string AeroDownforceMult {
            get {
                return ResourceManager.GetString("AeroDownforceMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aero factor.
        /// </summary>
        public static string AeroFactor {
            get {
                return ResourceManager.GetString("AeroFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Curve 0.
        /// </summary>
        public static string AICurve0 {
            get {
                return ResourceManager.GetString("AICurve0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Curve 1.
        /// </summary>
        public static string AICurve1 {
            get {
                return ResourceManager.GetString("AICurve1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Curve 2.
        /// </summary>
        public static string AICurve2 {
            get {
                return ResourceManager.GetString("AICurve2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Curve 3.
        /// </summary>
        public static string AICurve3 {
            get {
                return ResourceManager.GetString("AICurve3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Curve 4.
        /// </summary>
        public static string AICurve4 {
            get {
                return ResourceManager.GetString("AICurve4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Curve 5.
        /// </summary>
        public static string AICurve5 {
            get {
                return ResourceManager.GetString("AICurve5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Curve 6.
        /// </summary>
        public static string AICurve6 {
            get {
                return ResourceManager.GetString("AICurve6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Curve 7.
        /// </summary>
        public static string AICurve7 {
            get {
                return ResourceManager.GetString("AICurve7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI curves.
        /// </summary>
        public static string AICurves {
            get {
                return ResourceManager.GetString("AICurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antilock Brake System.
        /// </summary>
        public static string AntilockBrakeSystem {
            get {
                return ResourceManager.GetString("AntilockBrakeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic gearbox.
        /// </summary>
        public static string AutomaticGearbox {
            get {
                return ResourceManager.GetString("AutomaticGearbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body damage.
        /// </summary>
        public static string BodyDamage {
            get {
                return ResourceManager.GetString("BodyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake balance.
        /// </summary>
        public static string BrakeBalance {
            get {
                return ResourceManager.GetString("BrakeBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake blip.
        /// </summary>
        public static string BrakeBlip {
            get {
                return ResourceManager.GetString("BrakeBlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake decrease curve.
        /// </summary>
        public static string BrakeDecreaseCurve {
            get {
                return ResourceManager.GetString("BrakeDecreaseCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake increase curve.
        /// </summary>
        public static string BrakeIncreaseCurve {
            get {
                return ResourceManager.GetString("BrakeIncreaseCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera arm.
        /// </summary>
        public static string CameraArm {
            get {
                return ResourceManager.GetString("CameraArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to auto.
        /// </summary>
        public static string CopyToAuto {
            get {
                return ResourceManager.GetString("CopyToAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to front.
        /// </summary>
        public static string CopyToFront {
            get {
                return ResourceManager.GetString("CopyToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to manual.
        /// </summary>
        public static string CopyToManual {
            get {
                return ResourceManager.GetString("CopyToManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to rear.
        /// </summary>
        public static string CopyToRear {
            get {
                return ResourceManager.GetString("CopyToRear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive dynamics.
        /// </summary>
        public static string DriveDynamics {
            get {
                return ResourceManager.GetString("DriveDynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivetrain.
        /// </summary>
        public static string Drivetrain {
            get {
                return ResourceManager.GetString("Drivetrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine damage.
        /// </summary>
        public static string EngineDamage {
            get {
                return ResourceManager.GetString("EngineDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine tuning.
        /// </summary>
        public static string EngineTuning {
            get {
                return ResourceManager.GetString("EngineTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extr. turn spd. mod..
        /// </summary>
        public static string ExtrTurnSpdMod {
            get {
                return ResourceManager.GetString("ExtrTurnSpdMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final gear ratio.
        /// </summary>
        public static string FinalGearRatio {
            get {
                return ResourceManager.GetString("FinalGearRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front bias brake ratio.
        /// </summary>
        public static string FrontBiasBrakeRatio {
            get {
                return ResourceManager.GetString("FrontBiasBrakeRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front drive ratio.
        /// </summary>
        public static string FrontDriveRatio {
            get {
                return ResourceManager.GetString("FrontDriveRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front grip bias.
        /// </summary>
        public static string FrontGripBias {
            get {
                return ResourceManager.GetString("FrontGripBias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front tires.
        /// </summary>
        public static string FrontTires {
            get {
                return ResourceManager.GetString("FrontTires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas decrease curve.
        /// </summary>
        public static string GasDecreaseCurve {
            get {
                return ResourceManager.GetString("GasDecreaseCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas increase curve.
        /// </summary>
        public static string GasIncreaseCurve {
            get {
                return ResourceManager.GetString("GasIncreaseCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas off factor.
        /// </summary>
        public static string GasOffFactor {
            get {
                return ResourceManager.GetString("GasOffFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear efficiency.
        /// </summary>
        public static string GearEfficiency {
            get {
                return ResourceManager.GetString("GearEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear ratio factor.
        /// </summary>
        public static string GearRatioFactor {
            get {
                return ResourceManager.GetString("GearRatioFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear ratios.
        /// </summary>
        public static string GearRatios {
            get {
                return ResourceManager.GetString("GearRatios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear shift delay.
        /// </summary>
        public static string GearShiftDelay {
            get {
                return ResourceManager.GetString("GearShiftDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradual turn cutoff.
        /// </summary>
        public static string GradualTurnCutoff {
            get {
                return ResourceManager.GetString("GradualTurnCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G transfer factor.
        /// </summary>
        public static string GTransferFactor {
            get {
                return ResourceManager.GetString("GTransferFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High turn factor.
        /// </summary>
        public static string HighTurnFactor {
            get {
                return ResourceManager.GetString("HighTurnFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateral acc. grip mult..
        /// </summary>
        public static string LateralAccGripMult {
            get {
                return ResourceManager.GetString("LateralAccGripMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low turn factor.
        /// </summary>
        public static string LowTurnFactor {
            get {
                return ResourceManager.GetString("LowTurnFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual gearbox.
        /// </summary>
        public static string ManualGearbox {
            get {
                return ResourceManager.GetString("ManualGearbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass (Kg).
        /// </summary>
        public static string MassKg {
            get {
                return ResourceManager.GetString("MassKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max braking decel.
        /// </summary>
        public static string MaxBrakingDecel {
            get {
                return ResourceManager.GetString("MaxBrakingDecel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum RPM.
        /// </summary>
        public static string MaximumRPM {
            get {
                return ResourceManager.GetString("MaximumRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max velocity (m/s).
        /// </summary>
        public static string MaxVelocityMS {
            get {
                return ResourceManager.GetString("MaxVelocityMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium turn cutoff.
        /// </summary>
        public static string MediumTurnCutoff {
            get {
                return ResourceManager.GetString("MediumTurnCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med. turn spd. mod..
        /// </summary>
        public static string MedTurnSpdMod {
            get {
                return ResourceManager.GetString("MedTurnSpdMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum RPM.
        /// </summary>
        public static string MinimumRPM {
            get {
                return ResourceManager.GetString("MinimumRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min steering accel.
        /// </summary>
        public static string MinSteeringAccel {
            get {
                return ResourceManager.GetString("MinSteeringAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous carp data (affects car tuning in game, edit at your own risk).
        /// </summary>
        public static string MiscellaneousCarpData {
            get {
                return ResourceManager.GetString("MiscellaneousCarpData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of gears.
        /// </summary>
        public static string NumberOfGears {
            get {
                return ResourceManager.GetString("NumberOfGears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance metrics.
        /// </summary>
        public static string PerformanceMetrics {
            get {
                return ResourceManager.GetString("PerformanceMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch roll factor.
        /// </summary>
        public static string PitchRollFactor {
            get {
                return ResourceManager.GetString("PitchRollFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power steering.
        /// </summary>
        public static string PowerSteering {
            get {
                return ResourceManager.GetString("PowerSteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push factor.
        /// </summary>
        public static string PushFactor {
            get {
                return ResourceManager.GetString("PushFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realistic carp wizard.
        /// </summary>
        public static string RealisticCarpWizard {
            get {
                return ResourceManager.GetString("RealisticCarpWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear tires.
        /// </summary>
        public static string RearTires {
            get {
                return ResourceManager.GetString("RearTires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rim size.
        /// </summary>
        public static string RimSize {
            get {
                return ResourceManager.GetString("RimSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road bump factor.
        /// </summary>
        public static string RoadBumpFactor {
            get {
                return ResourceManager.GetString("RoadBumpFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Carp.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp turn cutoff.
        /// </summary>
        public static string SharpTurnCutoff {
            get {
                return ResourceManager.GetString("SharpTurnCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp turn spd. mod..
        /// </summary>
        public static string SharpTurnSpdMod {
            get {
                return ResourceManager.GetString("SharpTurnSpdMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift blip.
        /// </summary>
        public static string ShiftBlip {
            get {
                return ResourceManager.GetString("ShiftBlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide assistance factor.
        /// </summary>
        public static string SlideAssistanceFactor {
            get {
                return ResourceManager.GetString("SlideAssistanceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide multiplier.
        /// </summary>
        public static string SlideMultiplier {
            get {
                return ResourceManager.GetString("SlideMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide velocity cap.
        /// </summary>
        public static string SlideVelocityCap {
            get {
                return ResourceManager.GetString("SlideVelocityCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin velocity cap.
        /// </summary>
        public static string SpinVelocityCap {
            get {
                return ResourceManager.GetString("SpinVelocityCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoiler act. speed.
        /// </summary>
        public static string SpoilerActSpeed {
            get {
                return ResourceManager.GetString("SpoilerActSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoiler function type.
        /// </summary>
        public static string SpoilerFunctionType {
            get {
                return ResourceManager.GetString("SpoilerFunctionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering speed.
        /// </summary>
        public static string SteeringSpeed {
            get {
                return ResourceManager.GetString("SteeringSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdivide level.
        /// </summary>
        public static string SubdivideLevel {
            get {
                return ResourceManager.GetString("SubdivideLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension damage.
        /// </summary>
        public static string SuspensionDamage {
            get {
                return ResourceManager.GetString("SuspensionDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension stiffness.
        /// </summary>
        public static string SuspensionStiffness {
            get {
                return ResourceManager.GetString("SuspensionStiffness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncFeData3 with FeData.
        /// </summary>
        public static string SyncWithFeData {
            get {
                return ResourceManager.GetString("SyncWithFeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tire factor.
        /// </summary>
        public static string TireFactor {
            get {
                return ResourceManager.GetString("TireFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tire sidewall.
        /// </summary>
        public static string TireSidewall {
            get {
                return ResourceManager.GetString("TireSidewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tire wear.
        /// </summary>
        public static string TireWear {
            get {
                return ResourceManager.GetString("TireWear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tire width.
        /// </summary>
        public static string TireWidth {
            get {
                return ResourceManager.GetString("TireWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Speed (m/s).
        /// </summary>
        public static string TopSpeedMS {
            get {
                return ResourceManager.GetString("TopSpeedMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn circle radius.
        /// </summary>
        public static string TurnCircleRadius {
            get {
                return ResourceManager.GetString("TurnCircleRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn in ramp.
        /// </summary>
        public static string TurnInRamp {
            get {
                return ResourceManager.GetString("TurnInRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn out ramp.
        /// </summary>
        public static string TurnOutRamp {
            get {
                return ResourceManager.GetString("TurnOutRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity to RPM.
        /// </summary>
        public static string VelocityToRPM {
            get {
                return ResourceManager.GetString("VelocityToRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel base.
        /// </summary>
        public static string WheelBase {
            get {
                return ResourceManager.GetString("WheelBase", resourceCulture);
            }
        }
    }
}
