//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeDataPreviewView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeDataPreviewView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.FeDataPreviewView", typeof(FeDataPreviewView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 to 100 MPH.
        /// </summary>
        public static string Accel0To100 {
            get {
                return ResourceManager.GetString("Accel0To100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 to 60 MPH.
        /// </summary>
        public static string Accel0To60 {
            get {
                return ResourceManager.GetString("Accel0To60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration.
        /// </summary>
        public static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic FeData.
        /// </summary>
        public static string BasicFeData {
            get {
                return ResourceManager.GetString("BasicFeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic properties.
        /// </summary>
        public static string BasicProperties {
            get {
                return ResourceManager.GetString("BasicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakes.
        /// </summary>
        public static string Brakes {
            get {
                return ResourceManager.GetString("Brakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braking.
        /// </summary>
        public static string Braking {
            get {
                return ResourceManager.GetString("Braking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car class.
        /// </summary>
        public static string CarClass {
            get {
                return ResourceManager.GetString("CarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car ID.
        /// </summary>
        public static string CarId {
            get {
                return ResourceManager.GetString("CarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car name.
        /// </summary>
        public static string CarName {
            get {
                return ResourceManager.GetString("CarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 1.
        /// </summary>
        public static string Color1 {
            get {
                return ResourceManager.GetString("Color1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 10.
        /// </summary>
        public static string Color10 {
            get {
                return ResourceManager.GetString("Color10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 2.
        /// </summary>
        public static string Color2 {
            get {
                return ResourceManager.GetString("Color2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 3.
        /// </summary>
        public static string Color3 {
            get {
                return ResourceManager.GetString("Color3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 4.
        /// </summary>
        public static string Color4 {
            get {
                return ResourceManager.GetString("Color4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 5.
        /// </summary>
        public static string Color5 {
            get {
                return ResourceManager.GetString("Color5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 6.
        /// </summary>
        public static string Color6 {
            get {
                return ResourceManager.GetString("Color6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 7.
        /// </summary>
        public static string Color7 {
            get {
                return ResourceManager.GetString("Color7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 8.
        /// </summary>
        public static string Color8 {
            get {
                return ResourceManager.GetString("Color8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 9.
        /// </summary>
        public static string Color9 {
            get {
                return ResourceManager.GetString("Color9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement.
        /// </summary>
        public static string Displacement {
            get {
                return ResourceManager.GetString("Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver seat.
        /// </summary>
        public static string DriverSeat {
            get {
                return ResourceManager.GetString("DriverSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearbox.
        /// </summary>
        public static string Gearbox {
            get {
                return ResourceManager.GetString("Gearbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling.
        /// </summary>
        public static string Handling {
            get {
                return ResourceManager.GetString("Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History 1.
        /// </summary>
        public static string History1 {
            get {
                return ResourceManager.GetString("History1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History 2.
        /// </summary>
        public static string History2 {
            get {
                return ResourceManager.GetString("History2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History 3.
        /// </summary>
        public static string History3 {
            get {
                return ResourceManager.GetString("History3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History 4.
        /// </summary>
        public static string History4 {
            get {
                return ResourceManager.GetString("History4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History 5.
        /// </summary>
        public static string History5 {
            get {
                return ResourceManager.GetString("History5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History 6.
        /// </summary>
        public static string History6 {
            get {
                return ResourceManager.GetString("History6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History 7.
        /// </summary>
        public static string History7 {
            get {
                return ResourceManager.GetString("History7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History 8.
        /// </summary>
        public static string History8 {
            get {
                return ResourceManager.GetString("History8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is available to AI drivers.
        /// </summary>
        public static string IsAvailableToAI {
            get {
                return ResourceManager.GetString("IsAvailableToAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is bonus car.
        /// </summary>
        public static string IsBonus {
            get {
                return ResourceManager.GetString("IsBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a DLC car.
        /// </summary>
        public static string IsDlcCar {
            get {
                return ResourceManager.GetString("IsDlcCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is police car.
        /// </summary>
        public static string IsPolice {
            get {
                return ResourceManager.GetString("IsPolice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync edits on other FeData files / Carp.
        /// </summary>
        public static string LinkEdits {
            get {
                return ResourceManager.GetString("LinkEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, only non-localized fields are supported (basic props, compare and unknown values)..
        /// </summary>
        public static string LinkEditsNote {
            get {
                return ResourceManager.GetString("LinkEditsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum RPM.
        /// </summary>
        public static string MaxRpm {
            get {
                return ResourceManager.GetString("MaxRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tires.
        /// </summary>
        public static string Tires {
            get {
                return ResourceManager.GetString("Tires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top speed.
        /// </summary>
        public static string TopSpeed {
            get {
                return ResourceManager.GetString("TopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torque.
        /// </summary>
        public static string Torque {
            get {
                return ResourceManager.GetString("Torque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight distribution.
        /// </summary>
        public static string WeightDistr {
            get {
                return ResourceManager.GetString("WeightDistr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
