//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FshEditorView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FshEditorView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.FshEditorView", typeof(FshEditorView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add texture.
        /// </summary>
        public static string AddTexture {
            get {
                return ResourceManager.GetString("AddTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background:.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash editor....
        /// </summary>
        public static string DashEditor {
            get {
                return ResourceManager.GetString("DashEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit coordinates.
        /// </summary>
        public static string EditCoords {
            get {
                return ResourceManager.GetString("EditCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer data.
        /// </summary>
        public static string FooterData {
            get {
                return ResourceManager.GetString("FooterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH blob details.
        /// </summary>
        public static string FshBlobDetails {
            get {
                return ResourceManager.GetString("FshBlobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH blob footer.
        /// </summary>
        public static string FshBlobFooter {
            get {
                return ResourceManager.GetString("FshBlobFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH blob options.
        /// </summary>
        public static string FshBlobOptions {
            get {
                return ResourceManager.GetString("FshBlobOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH options.
        /// </summary>
        public static string FshOptions {
            get {
                return ResourceManager.GetString("FshOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image offset.
        /// </summary>
        public static string ImageOffset {
            get {
                return ResourceManager.GetString("ImageOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel data size.
        /// </summary>
        public static string PixelDataSize {
            get {
                return ResourceManager.GetString("PixelDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel format.
        /// </summary>
        public static string PixelFormat {
            get {
                return ResourceManager.GetString("PixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace....
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation axis.
        /// </summary>
        public static string RotationAxis {
            get {
                return ResourceManager.GetString("RotationAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show edit controls.
        /// </summary>
        public static string ShowEditCtrls {
            get {
                return ResourceManager.GetString("ShowEditCtrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
