//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.SettingsView", typeof(SettingsView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup files upon saving.
        /// </summary>
        public static string BackupFilesUponSaving {
            get {
                return ResourceManager.GetString("BackupFilesUponSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Serial numbers.
        /// </summary>
        public static string CheckSerialNumbers {
            get {
                return ResourceManager.GetString("CheckSerialNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable cleanup tasks on FCE files when saving a VIV file.
        /// </summary>
        public static string EnableCleanupTasksOnFCEFilesWhenSavingAVIVFile {
            get {
                return ResourceManager.GetString("EnableCleanupTasksOnFCEFilesWhenSavingAVIVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable serial number checkup when saving a VIV file.
        /// </summary>
        public static string EnableSerialNumberCheckupWhenSavingAVIVFile {
            get {
                return ResourceManager.GetString("EnableSerialNumberCheckupWhenSavingAVIVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCE cleanup.
        /// </summary>
        public static string FCECleanup {
            get {
                return ResourceManager.GetString("FCECleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File backup.
        /// </summary>
        public static string FileBackup {
            get {
                return ResourceManager.GetString("FileBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nfs3.exe launch arguments.
        /// </summary>
        public static string Nfs3ExeLaunchArguments {
            get {
                return ResourceManager.GetString("Nfs3ExeLaunchArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFS3 Root directory.
        /// </summary>
        public static string NFS3RootDirectory {
            get {
                return ResourceManager.GetString("NFS3RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFS3 settings.
        /// </summary>
        public static string NFS3Settings {
            get {
                return ResourceManager.GetString("NFS3Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of recent files to keep on the list.
        /// </summary>
        public static string NumberOfRecentFilesToKeepOnTheList {
            get {
                return ResourceManager.GetString("NumberOfRecentFilesToKeepOnTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIV editor.
        /// </summary>
        public static string VIVEditor {
            get {
                return ResourceManager.GetString("VIVEditor", resourceCulture);
            }
        }
    }
}
