//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Vivianne.Resources.Strings.Views; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class VivInfoView {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal VivInfoView() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Vivianne.Resources.Strings.Views.VivInfoView", typeof(VivInfoView).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has separate sim-physics car performance data.
    /// </summary>
    public static string CarpSim {
        get {
            return ResourceManager.GetString("CarpSim", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Directory size: {0} files.
    /// </summary>
    public static string DirSize {
        get {
            return ResourceManager.GetString("DirSize", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Export all files.
    /// </summary>
    public static string ExportAll {
        get {
            return ResourceManager.GetString("ExportAll", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Features.
    /// </summary>
    public static string Features {
        get {
            return ResourceManager.GetString("Features", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has english (british) FeData.
    /// </summary>
    public static string FeDataBri {
        get {
            return ResourceManager.GetString("FeDataBri", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has english (US) FeData.
    /// </summary>
    public static string FeDataEng {
        get {
            return ResourceManager.GetString("FeDataEng", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has french FeData.
    /// </summary>
    public static string FeDataFre {
        get {
            return ResourceManager.GetString("FeDataFre", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has german FeData.
    /// </summary>
    public static string FeDataGer {
        get {
            return ResourceManager.GetString("FeDataGer", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has italian FeData.
    /// </summary>
    public static string FeDataIta {
        get {
            return ResourceManager.GetString("FeDataIta", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has spanish FeData.
    /// </summary>
    public static string FeDataSpa {
        get {
            return ResourceManager.GetString("FeDataSpa", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has swedish FeData.
    /// </summary>
    public static string FeDataSwe {
        get {
            return ResourceManager.GetString("FeDataSwe", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Estimated file size: {0}.
    /// </summary>
    public static string FileSize {
        get {
            return ResourceManager.GetString("FileSize", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has basic engine sound effects.
    /// </summary>
    public static string HasBnk {
        get {
            return ResourceManager.GetString("HasBnk", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has car mesh.
    /// </summary>
    public static string HasCarFce {
        get {
            return ResourceManager.GetString("HasCarFce", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has dashboard FSH.
    /// </summary>
    public static string HasDash {
        get {
            return ResourceManager.GetString("HasDash", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Has in-menu FSH car logo.
    /// </summary>
    public static string HasFedataFsh {
        get {
            return ResourceManager.GetString("HasFedataFsh", resourceCulture);
        }
    }
}
